org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true

kotlin.code.style=official

libraryReadableName=Fabric Mod JSON Serialization
libraryDescription=A library to serialize or deserizlize fabric.mod.json in fabric mod.
libraryGroup=io.github.xueria
libraryName=fabric-json-serialization
libraryVersion=1.0.0-alpha.1

