[versions]
# https://kotlinlang.org/docs/home.html
kotlin = "2.4.10"
# https://github.com/Kotlin/kotlinx.serialization/releases/latest
kotlinx-serialization = "1.11.0"

# https://github.com/vanniktech/gradle-maven-publish-plugin/releases/latest
vanniktech-maven-publish = "0.37.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }

[libraries]
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

[bundles]
